package xuyihao.tools;

/**
 * created by xuyihao on 2016/5/15
 * @author johnson
 * @description 符合MIME标准的文件类型的枚举
 * */
public enum MIME_FileType {
	 
	Application_bin("application/octet-stream"),
	Application_class("application/octet-stream"),
	Application_dir("application/x-director"),
	Application_dll("application/x-msdownload"),
	Application_exe("application/octet-stream"),
	Application_flv("flv-application/octet-stream"),
	Application_zip("application/zip"),
	Application_apk("application/vnd.android.package-archive"),
	Application_rar("application/octet-stream"),
	Application_war("application/octet-stream"),
	Application_gtar("application/x-gtar"),
	Application_gz("application/x-gzip"),
	Application_jam("application/x-jam"),
	Application_jar("application/java-archive"),
	Application_js("application/x-javascript"),
	Application_pdb("chemical/x-pdb"),
	Application_pdf("application/pdf"),
	Application_proxy("application/x-ns-proxy-autoconfig"),
	Application_sh("application/x-sh"),
	Application_shar("application/x-shar"),
	Application_t("application/x-troff"),
	Application_tar("application/x-tar"),
	Application_taz("application/x-tar"),
	Application_tex("application/x-tex"),
	Application_tgz("application/x-compressed"),
	Application_wdb("application/vnd.ms-works"),
	Application_web("application/vnd.xara"),
	Application_wmd("application/x-ms-wmd"),
	Application_wmf("application/x-msmetafile"),
	Application_xht("application/xhtml+xml"),
	Application_xhtm("application/xhtml+xml"),
	Application_xhtml("application/xhtml+xml"),
	Application_json("application/json"),
	Text_txt("text/plain"),
	Text_conf("text/plain"),
	Text_cpp("text/plain"),
	Text_css("text/css"),
	Text_lrc("application/octet-stream"),
	Text_sql("application/octet-stream"),
	Text_c("text/plain"),
	Text_h("text/plain"),
	Text_htm("text/html"),
	Text_html("text/html"),
	Text_hts("text/html"),
	Text_htt("text/webviewhtml"),
	Text_jad("text/text/vnd.sun.j2me.app-descriptor"),
	Text_java("text/plain"),
	Text_log("text/plain"),
	Text_prop("text/plain"),
	Text_rt("text/vnd.rn-realtext"),
	Video_avi("video/x-msvideo"),
	Video_3gp("video/3gpp"),
	Video_asf("video/x-ms-asf"),
	Video_asx("video/x-ms-asf"),
	Video_mov("video/quicktime"),
	Video_movie("video/x-sgi-movie"),
	Video_mp2("video/mpeg"),
	Video_mp4("video/mp4"),
	Video_mpa("video/mpeg"),
	Video_mpe("video/mpeg"),
	Video_mpeg("video/mpeg"),
	Video_mpg("video/mpeg"),
	Video_mpg4("video/mp4"),
	Video_wm("video/x-ms-wm"),
	Audio_mp3("audio/mpeg"),
	Audio_mpga("audio/mpeg"),
	Audio_aif("audio/x-aiff"),
	Audio_aifc("audio/x-aiff"),
	Audio_aiff("audio/x-aiff"),
	Audio_ra("audio/x-pn-realaudio"),
	Audio_ram("audio/x-pn-realaudio"),
	Audio_rm("audio/x-pn-realaudio"),
	Audio_rmm("audio/x-pn-realaudio"),
	Audio_rmvb("audio/x-pn-realaudio"),
	Audio_rmf("audio/x-rmf"),
	Audio_rmi("audio/mid"),
	Audio_wma("audio/x-ms-wma"),
	MicrosoftEXCEL_xls("application/vnd.ms-excel"),
	MicrosoftEXCEL_xla("application/vnd.ms-excel"),
	MicrosoftEXCEL_xlc("application/vnd.ms-excel"),
	MicrosoftEXCEL_xlm("application/vnd.ms-excel"),
	MicrosoftEXCEL_xlt("application/vnd.ms-excel"),
	MicrosoftEXCEL_xlw("application/vnd.ms-excel"),
	MicrosoftVISIO_vsd("application/vnd.ms-visio.drawing"),
	MicrosoftWORD_doc("application/msword"),
	MicrosoftWORD_docx("application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
	MicrosoftWORD_dot("application/msword"),
	MicrosoftPPT_pot("application/vnd.ms-powerpoint"),
	MicrosoftPPT_pps("application/vnd.ms-powerpoint"),
	MicrosoftPPT_ppt("application/vnd.ms-powerpoint"),
	MicrosoftPPT_pptx("application/vnd.openxmlformats-officedocument.presentationml.presentation"),
	Image_jpeg("image/jpeg"),
	Image_jpe("image/jpeg"),
	Image_jpg("image/jpeg"),
	Image_jpz("image/jpeg"),
	Image_png("image/png"),
	Image_pnz("image/png"),
	Image_gif("image/gif"),
	Image_ief("image/ief"),
	Image_ifs("image/ifs"),
	Image_ppm("image/image/x-portable-pixmap"),
	Image_ifm("image/gif"),
	Image_svg("image/svg+xml"),
	Image_svf("image/vnd");
	
	private final String value;
	
	private MIME_FileType(String v){
		this.value = v;
	}
	
	public String getValue(){
		return this.value;
	}
}